version: '3'

services:
  apache:
    image: nbassistant_apache:latest
    ports:
      - "5000:80"
    restart: "no"
    environment:
      MYSQL_HOST: 10.250.196.180:3307
      MYSQL_USER: twist
      MYSQL_PASSWORD: twist