version: '3'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - "./mysql/conf.d:/etc/mysql/conf.d"
      - "mysqldata:/var/lib/mysql"
    restart: "no"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: nba
      MYSQL_DATABASE: nbassistant
      MYSQL_USER: twist
      MYSQL_PASSWORD: twist

  apache:
    depends_on:
      - mysql
    image: nbassistant_apache:latest
    ports:
      - "5000:80"
    restart: "no"
    environment:
      MYSQL_HOST: mysql:3306
      MYSQL_USER: twist
      MYSQL_PASSWORD: twist

# These volumes will be shared by all services.
volumes:
  mysqldata: